spring:
  datasource:
    url: jdbc:mariadb:loadbalance://34.23.29.201:3306,35.243.216.21:3306/singasm3?autoReconnect=true&failOverReadOnly=false
    username: test_remote
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
retry:
  maxAttempts: 5
logging:
  config: classpath:logback-spring.xml
